# Generated by Django 5.2.17 on 2026-09-30 04:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['nombre'], 'permissions': [('puede_reasignar_categorias', 'Puede cambiar la categoría de un producto')], 'verbose_name': 'categoría', 'verbose_name_plural': 'categorías'},
        ),
        migrations.AlterModelOptions(
            name='movimientostock',
            options={'ordering': ['-fecha'], 'permissions': [('puede_anular_movimiento', 'Puede anular un movimiento de stock')], 'verbose_name_plural': 'movimientos de stock'},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['-fecha_registro'], 'permissions': [('puede_ver_precios', 'Puede ver y modificar los precios de venta'), ('puede_ajustar_stock', 'Puede ajustar el stock sin registrar un movimiento')]},
        ),
        migrations.AddField(
            model_name='categoria',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categorias_creadas', to=settings.AUTH_USER_MODEL, verbose_name='creado por'),
        ),
        migrations.AddField(
            model_name='movimientostock',
            name='registrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_registrados', to=settings.AUTH_USER_MODEL, verbose_name='registrado por'),
        ),
        migrations.AddField(
            model_name='producto',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True, verbose_name='actualizado en'),
        ),
        migrations.AddField(
            model_name='producto',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_creados', to=settings.AUTH_USER_MODEL, verbose_name='creado por'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='sku',
            field=models.CharField(help_text='Usa mayúsculas, números y guiones. Ejemplo: ABE-1001-AB.', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='El SKU solo admite letras mayúsculas, números y guiones (ejemplo: ABE-1001-AB).', regex='^[A-Z0-9]+(-[A-Z0-9]+)*$')]),
        ),
    ]
