# Generated by Django 5.2.17 on 2026-09-30 04:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('ADMINISTRADOR', 'Administrador'), ('BODEGUERO', 'Bodeguero'), ('VENDEDOR', 'Vendedor')], default='VENDEDOR', max_length=20, verbose_name='rol')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='teléfono')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'perfil de usuario',
                'verbose_name_plural': 'perfiles de usuario',
                'ordering': ['rol', 'usuario__username'],
                'permissions': [('puede_asignar_roles', 'Puede asignar y cambiar roles de los usuarios'), ('puede_ver_cuentas', 'Puede ver el listado de cuentas del sistema')],
            },
        ),
    ]
